<Workspace Version="0.7.0.23565" X="132.999290822936" Y="262.465818847967" zoom="0.92366106314192" Description="" Category="" Name="Home">
  <Elements>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="9953c9c8-e756-4563-a5b5-1d32d5058dd9" nickname="Python Script" x="239.563213636796" y="-141.550237054116" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variable.
print 555555555555

IN = IN
#Assign your output to the OUT variable
OUT = Point.ByCoordinates(IN[0][0],IN[0][1],0)</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="ca5c7b32-bed6-4fc4-810a-34574089758a" nickname="Watch" x="426.462378726945" y="-140.709786262084" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="4e4fd8a5-8af5-4080-82ad-07a4764e1442" nickname="Code Block" x="-56" y="-159" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="1..2;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="9953c9c8-e756-4563-a5b5-1d32d5058dd9" start_index="0" end="ca5c7b32-bed6-4fc4-810a-34574089758a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="4e4fd8a5-8af5-4080-82ad-07a4764e1442" start_index="0" end="9953c9c8-e756-4563-a5b5-1d32d5058dd9" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>